server:
  port: 8082

spring:
  datasource:
    url: jdbc:h2:mem:books;DB_CLOSE_DELAY=-1
    username: jeremy
    password: jeremy
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
